backend:
  name: git-gateway
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "menu"
    label: "Menu"
    folder: "content/menu"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Nazwa dania", name: "title", widget: "string" }
      - { label: "Cena", name: "price", widget: "string" }
      - { label: "Opis", name: "body", widget: "text" }

  - name: "info"
    label: "Informacje"
    files:
      - file: "content/info.md"
        label: "Informacje o restauracji"
        name: "info"
        fields:
          - { label: "Godziny otwarcia", name: "hours", widget: "string" }
          - { label: "Adres", name: "address", widget: "string" }
          - { label: "Telefon", name: "phone", widget: "string" }
